version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          no_output_timeout: 30m
          command: |
            npm run test
workflows:
  build_test:
    jobs:
      - run_tests
